version: '3'

services:
  web:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
  api:
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING="true"
    ports:
      - 8000:3000